name = "honocms"
main = "src/main.tsx"
compatibility_date = "2024-12-30"
account_id = ""

[dev]
port = 8788

[assets]
directory = "public"


[observability.logs]
enabled = true


[[r2_buckets]]
bucket_name = "honocms-r2"
binding = "honocms_r2"

[vars] # s3相关的
ACCOUNT_ID = ""
ACCESS_KEY_ID = ""
SECRET_ACCESS_KEY = ""
R2_BUCKET_NAME = "chonocms-r2"
APP_STATIC_URL = "https://xxx.honocms.com" #注意最后不用加/

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "honocms_db"
database_id = ""
#preview_database_id = "DB" # Required for Pages local development
#migrations_dir = "drizzle"
migrations_dir = "drizzle"
migrations_table = "d1_migrations"

